name: picc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  uuid: ^3.0.6
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  cached_network_image: ^3.2.3

flutter:

  uses-material-design: true
