// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL2sSCBCNLok5whct9E6t-w-XY6C9GEXQ',
    appId: '1:106249513096:web:bb63b32da6935a89be973d',
    messagingSenderId: '106249513096',
    projectId: 'piccapp-d15bc',
    authDomain: 'piccapp-d15bc.firebaseapp.com',
    storageBucket: 'piccapp-d15bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByCMm0exjlmdaV7zU-nqLSheO5Rp8H0s0',
    appId: '1:106249513096:android:27998f36422ae196be973d',
    messagingSenderId: '106249513096',
    projectId: 'piccapp-d15bc',
    storageBucket: 'piccapp-d15bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUa5LWuRlvg-gwT2356q_l45gMCptqrYw',
    appId: '1:106249513096:ios:3d0f9031695e0b8dbe973d',
    messagingSenderId: '106249513096',
    projectId: 'piccapp-d15bc',
    storageBucket: 'piccapp-d15bc.firebasestorage.app',
    iosBundleId: 'no.picc.picc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUa5LWuRlvg-gwT2356q_l45gMCptqrYw',
    appId: '1:106249513096:ios:3d0f9031695e0b8dbe973d',
    messagingSenderId: '106249513096',
    projectId: 'piccapp-d15bc',
    storageBucket: 'piccapp-d15bc.firebasestorage.app',
    iosBundleId: 'no.picc.picc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL2sSCBCNLok5whct9E6t-w-XY6C9GEXQ',
    appId: '1:106249513096:web:7eadca4c10388c0cbe973d',
    messagingSenderId: '106249513096',
    projectId: 'piccapp-d15bc',
    authDomain: 'piccapp-d15bc.firebaseapp.com',
    storageBucket: 'piccapp-d15bc.firebasestorage.app',
  );
}
